name: Bank Migration CI/CD Pipeline

on:
  push:
    branches: [ development, uat, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: npm test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying to Staging..."

  migration:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: node src/migration/migrate.js

  reconcile:
    runs-on: ubuntu-latest
    needs: migration
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: node src/reconciliation/reconcile.js

  approval:
    runs-on: ubuntu-latest
    needs: reconcile
    steps:
      - run: echo "Waiting for approval..."

  production:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - run: echo "Deploying to Production...."